var searchData=
[
  ['iaccountservice_0',['IAccountService',['../interfaceBistroQ_1_1Core_1_1Interfaces_1_1Services_1_1IAccountService.html',1,'BistroQ::Core::Interfaces::Services']]],
  ['icategoryrepository_1',['ICategoryRepository',['../interfaceBistroQ_1_1Core_1_1Interfaces_1_1Repositories_1_1ICategoryRepository.html',1,'BistroQ::Core::Interfaces::Repositories']]],
  ['icategoryservice_2',['ICategoryService',['../interfaceBistroQ_1_1Core_1_1Interfaces_1_1Services_1_1ICategoryService.html',1,'BistroQ::Core::Interfaces::Services']]],
  ['icloudstorageservice_3',['ICloudStorageService',['../interfaceBistroQ_1_1Core_1_1Interfaces_1_1Services_1_1ICloudStorageService.html',1,'BistroQ::Core::Interfaces::Services']]],
  ['ifileservice_4',['IFileService',['../interfaceBistroQ_1_1Core_1_1Interfaces_1_1Services_1_1IFileService.html',1,'BistroQ::Core::Interfaces::Services']]],
  ['igenericrepository_5',['IGenericRepository',['../interfaceBistroQ_1_1Core_1_1Interfaces_1_1Repositories_1_1IGenericRepository.html',1,'BistroQ::Core::Interfaces::Repositories']]],
  ['igenericrepository_3c_20category_20_3e_6',['IGenericRepository&lt; Category &gt;',['../interfaceBistroQ_1_1Core_1_1Interfaces_1_1Repositories_1_1IGenericRepository.html',1,'BistroQ::Core::Interfaces::Repositories']]],
  ['igenericrepository_3c_20image_20_3e_7',['IGenericRepository&lt; Image &gt;',['../interfaceBistroQ_1_1Core_1_1Interfaces_1_1Repositories_1_1IGenericRepository.html',1,'BistroQ::Core::Interfaces::Repositories']]],
  ['igenericrepository_3c_20nutritionfact_20_3e_8',['IGenericRepository&lt; NutritionFact &gt;',['../interfaceBistroQ_1_1Core_1_1Interfaces_1_1Repositories_1_1IGenericRepository.html',1,'BistroQ::Core::Interfaces::Repositories']]],
  ['igenericrepository_3c_20order_20_3e_9',['IGenericRepository&lt; Order &gt;',['../interfaceBistroQ_1_1Core_1_1Interfaces_1_1Repositories_1_1IGenericRepository.html',1,'BistroQ::Core::Interfaces::Repositories']]],
  ['igenericrepository_3c_20orderitem_20_3e_10',['IGenericRepository&lt; OrderItem &gt;',['../interfaceBistroQ_1_1Core_1_1Interfaces_1_1Repositories_1_1IGenericRepository.html',1,'BistroQ::Core::Interfaces::Repositories']]],
  ['igenericrepository_3c_20product_20_3e_11',['IGenericRepository&lt; Product &gt;',['../interfaceBistroQ_1_1Core_1_1Interfaces_1_1Repositories_1_1IGenericRepository.html',1,'BistroQ::Core::Interfaces::Repositories']]],
  ['igenericrepository_3c_20table_20_3e_12',['IGenericRepository&lt; Table &gt;',['../interfaceBistroQ_1_1Core_1_1Interfaces_1_1Repositories_1_1IGenericRepository.html',1,'BistroQ::Core::Interfaces::Repositories']]],
  ['igenericrepository_3c_20zone_20_3e_13',['IGenericRepository&lt; Zone &gt;',['../interfaceBistroQ_1_1Core_1_1Interfaces_1_1Repositories_1_1IGenericRepository.html',1,'BistroQ::Core::Interfaces::Repositories']]],
  ['iimagerepository_14',['IImageRepository',['../interfaceBistroQ_1_1Core_1_1Interfaces_1_1Repositories_1_1IImageRepository.html',1,'BistroQ::Core::Interfaces::Repositories']]],
  ['image_15',['Image',['../classBistroQ_1_1Core_1_1Entities_1_1Image.html',1,'BistroQ::Core::Entities']]],
  ['imagedto_16',['ImageDto',['../classBistroQ_1_1Core_1_1Dtos_1_1Image_1_1ImageDto.html',1,'BistroQ::Core::Dtos::Image']]],
  ['imagerepository_17',['ImageRepository',['../classBistroQ_1_1Infrastructure_1_1Repositories_1_1ImageRepository.html',1,'BistroQ::Infrastructure::Repositories']]],
  ['imagerequestdto_18',['ImageRequestDto',['../classBistroQ_1_1Core_1_1Dtos_1_1Image_1_1ImageRequestDto.html',1,'BistroQ::Core::Dtos::Image']]],
  ['imageurlresolver_19',['ImageUrlResolver',['../classBistroQ_1_1Core_1_1Mappings_1_1ImageUrlResolver.html',1,'BistroQ::Core::Mappings']]],
  ['inutritionfactrepository_20',['INutritionFactRepository',['../interfaceBistroQ_1_1Core_1_1Interfaces_1_1Repositories_1_1INutritionFactRepository.html',1,'BistroQ::Core::Interfaces::Repositories']]],
  ['iorderitemrepository_21',['IOrderItemRepository',['../interfaceBistroQ_1_1Core_1_1Interfaces_1_1Repositories_1_1IOrderItemRepository.html',1,'BistroQ::Core::Interfaces::Repositories']]],
  ['iorderitemservice_22',['IOrderItemService',['../interfaceBistroQ_1_1Core_1_1Interfaces_1_1Services_1_1IOrderItemService.html',1,'BistroQ::Core::Interfaces::Services']]],
  ['iorderrepository_23',['IOrderRepository',['../interfaceBistroQ_1_1Core_1_1Interfaces_1_1Repositories_1_1IOrderRepository.html',1,'BistroQ::Core::Interfaces::Repositories']]],
  ['iorderservice_24',['IOrderService',['../interfaceBistroQ_1_1Core_1_1Interfaces_1_1Services_1_1IOrderService.html',1,'BistroQ::Core::Interfaces::Services']]],
  ['ipaymentservice_25',['IPaymentService',['../interfaceBistroQ_1_1Core_1_1Interfaces_1_1Services_1_1IPaymentService.html',1,'BistroQ::Core::Interfaces::Services']]],
  ['iproductrepository_26',['IProductRepository',['../interfaceBistroQ_1_1Core_1_1Interfaces_1_1Repositories_1_1IProductRepository.html',1,'BistroQ::Core::Interfaces::Repositories']]],
  ['iproductservice_27',['IProductService',['../interfaceBistroQ_1_1Core_1_1Interfaces_1_1Services_1_1IProductService.html',1,'BistroQ::Core::Interfaces::Services']]],
  ['itablerepository_28',['ITableRepository',['../interfaceBistroQ_1_1Core_1_1Interfaces_1_1Repositories_1_1ITableRepository.html',1,'BistroQ::Core::Interfaces::Repositories']]],
  ['itableservice_29',['ITableService',['../interfaceBistroQ_1_1Core_1_1Interfaces_1_1Services_1_1ITableService.html',1,'BistroQ::Core::Interfaces::Services']]],
  ['itokenservice_30',['ITokenService',['../interfaceBistroQ_1_1Core_1_1Interfaces_1_1Services_1_1ITokenService.html',1,'BistroQ::Core::Interfaces::Services']]],
  ['iunitofwork_31',['IUnitOfWork',['../interfaceBistroQ_1_1Core_1_1Interfaces_1_1IUnitOfWork.html',1,'BistroQ::Core::Interfaces']]],
  ['izonerepository_32',['IZoneRepository',['../interfaceBistroQ_1_1Core_1_1Interfaces_1_1Repositories_1_1IZoneRepository.html',1,'BistroQ::Core::Interfaces::Repositories']]],
  ['izoneservice_33',['IZoneService',['../interfaceBistroQ_1_1Core_1_1Interfaces_1_1Services_1_1IZoneService.html',1,'BistroQ::Core::Interfaces::Services']]]
];
